---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-plex
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: media
  resources:
    requests:
      storage: 1Mi # Size does not matter ...twss
