---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx

spec:
  auto_upgrade: true
  task_privileged: true
  web_replicas: 2
  task_replicas: 2
  ingress_type: ingress
  ingress_class_name: internal
  hostname: awx.${SECRET_DOMAIN}
  ingress_annotations: |
    cert-manager.io/cluster-issuer: gts-production
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: "384"
    external-dns.home.arpa/enabled: "true
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
  ingress_tls_secret: awx-tls-custom-secret
  secret_key_secret: custom-awx-secret-key
  postgres_configuration_secret: awx-external-db-secret
