---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx

spec:
  auto_upgrade: true
  task_privileged: true
  web_replicas: 2
  task_replicas: 2
  ingress_type: ingress
  ingress_class_name: internal
  hostname: awx.${SECRET_DOMAIN}
  ingress_annotations: |
    cert-manager.io/cluster-issuer: gts-production
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: "384"
    nginx.ingress.kubernetes.io/auth-url: http://authelia.default.svc.cluster.local/api/verify
    nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
  ingress_tls_secret: awx-tls-custom-secret
  secret_key_secret: custom-awx-secret-key
  postgres_configuration_secret: awx-external-db-secret
