---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: grafana
        group: external
        url: https://grafana.monitoring.svc.cluster.local/api/health
        interval: 1m
        client:
          dns-resolver: tcp://10.43.0.10:53
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
