---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent-orphaned
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: downloads
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "@daily"
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 100
            supplementalGroups:
              - 34
              - 100
              - 10000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: ghcr.io/buroa/qbittools
              tag: v0.9.5@sha256:9f23effa85ce39a1e7acef313f88fdb7e9438700fb8c6227d7b085321dfb7409
              pullPolicy: IfNotPresent
            args: [
              "orphaned",
              "--exclude-pattern", "*_unpackerred",
              "--exclude-pattern", "*/manual/*",
              "--exclude-pattern", "*/music.import/*",
              # "--dry-run",
              "--server", "qbittorrent.downloads.svc.cluster.local",
              "--port", "8080"
            ]
            securityContext:
              runAsUser: 568
              runAsGroup: 100
    service:
      main:
        enabled: false
    persistence:
      media:
        enabled: true
        existingClaim: media
    resources:
      requests:
        memory: 250Mi
        cpu: 25m
      limits:
        memory: 500Mi
