apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gts-production
spec:
  acme:
    server: "${CERT_SERVER}"
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: gts-prod-secret
    externalAccountBinding:
      keyID: "${EABkeyID}"
      keySecretRef:
        name: cert-manager-gts-secret
        key: secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-gts-secret
              key: api-token
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
