---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539
        initContainers:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 14.9
        envFrom: &envFrom
          - secretRef:
              name: prowlarr-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr-develop
              tag: 1.9.1.3981@sha256:880e6e6c2600b3725a6172aa547caf6d8eb883dab50637a35bcce66a04eb39c6
            env:
              TZ: America/New_York
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 80
              PROWLARR__LOG_LEVEL: info
              PROWLARR__AUTHENTICATION_METHOD: External
              PROWLARR__THEME: dark
            envFrom: *envFrom
            securityContext:
              runAsUser: 568
              runAsGroup: 568

          gluetun:
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: latest
            securityContext:
               privileged: true
            networkPolicy:
              enabled: false
            env:
              - name: VPN_INTERFACE
                value: wg0
              - name: VPN_ENDPOINT_PORT
                value: "51820"
              - name: FIREWALL_INPUT_PORTS
                value: "80"
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: DNS_ADDRESS
                value: "127.0.0.2"
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: WIREGUARD_PRIVATE_KEY
              - name: WIREGUARD_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: WIREGUARD_PUBLIC_KEY
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: WIREGUARD_ADDRESSES
              - name: VPN_SERVICE_PROVIDER
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: VPN_SERVICE_PROVIDER
              - name: VPN_TYPE
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: VPN_TYPE
              - name: VPN_ENDPOINT_IP
                valueFrom:
                  secretKeyRef:
                    name: prowlarr-secret
                    key: VPN_ENDPOINT_IP

          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.1

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: emptyDir
      dnsdist-config:
        type: configMap
        name: prowlarr-dnsdist
        advancedMounts:
          main:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
