---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 100
            supplementalGroups:
              - 34
              - 100
              - 10000
            fsGroupChangePolicy: "OnRootMismatch"
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9@sha256:170970a909f892149cbf99be8d86c26f0090bc7d2fbd1c34dd770b4bf7e08458
            envFrom: &envFrom
              - secretRef:
                  name: sonarr-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.0.700@sha256:9ae40655d519479d4d70a8d67f929142a0fc2d10df0b75a0947ee3a6c8da7f53
              pullPolicy: IfNotPresent
            env:
              TZ: America/New_York
              PUSHOVER_DEBUG: "false"
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 80
              SONARR__LOG_LEVEL: info
              SONARR__AUTHENTICATION_METHOD: Basic
              SONARR__THEME: dark
            envFrom: *envFrom
            securityContext:
              runAsUser: 568
              runAsGroup: 100

          gluetun:
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: latest@sha256:8bb0ea2f18624dcf86bd5b13c0e781d2e72a6b0a3f32fbc0198d5663df65295f
            securityContext:
              privileged: true
            networkPolicy:
              enabled: false
            env:
              - name: VPN_INTERFACE
                value: wg0
              - name: VPN_ENDPOINT_PORT
                value: "51820"
              - name: FIREWALL_INPUT_PORTS
                value: "80"
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: DNS_SERVER
                value: "127.0.0.2"
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: WIREGUARD_PRIVATE_KEY
              - name: WIREGUARD_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: WIREGUARD_PUBLIC_KEY
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: WIREGUARD_ADDRESSES
              - name: VPN_SERVICE_PROVIDER
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: VPN_SERVICE_PROVIDER
              - name: VPN_TYPE
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: VPN_TYPE
              - name: VPN_ENDPOINT_IP
                valueFrom:
                  secretKeyRef:
                    name: sonarr-secret
                    key: VPN_ENDPOINT_IP

          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.2@sha256:06584eb44627c46b3718ee754c36a81acf66fdf423b162cae9ecfa69bb362c9e

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-proxy-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: https://sonarr.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sonarr-cert
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      scripts:
        enabled: true
        type: configMap
        name: sonarr-configmap
        subPath: pushover-notify.sh
        mountPath: /scripts/pushover-notify.sh
        defaultMode: 0775
        readOnly: true
      media:
        enabled: true
        existingClaim: media
      dnsdist-config:
        type: configMap
        name: sonarr-dnsdist
        advancedMounts:
          main:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true
      sonarr-resolv-config:
        type: configMap
        name: sonarr-resolv
        advancedMounts:
          main:
            main:
              - path: /etc/resolv.conf
                subPath: resolv.conf
                readOnly: true
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
