apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    issuerURL: ENC[AES256_GCM,data:snV0yX5onbFO38z8ZomRIHCZZRiusw54pJuzEHihcvHkAf0O52gjXjZTSJQ8CUo=,iv:wxL5PYVOkKNUyJ4DSoeMrgU4YEHrLeXFtaUGZN0c5Zw=,tag:m0z5DlW0hP3T92K88gX7Ew==,type:str]
    clientID: ENC[AES256_GCM,data:49WM+EL2Bnwj7fDKVfY4mTqT5AcoFSZj3HYY7JUCmruJOT9sgt3+Rw==,iv:SottfBWTlztFWesuM/YptY340LY8o/F7YUw/B41+QHQ=,tag:XMTEGgybWCRUO3tqlzYvNg==,type:str]
    clientSecret: ENC[AES256_GCM,data:nR2notL2+haOqlbOPYkrfT10mbO0Z4l0kbvbrnBVGSpqhk819ePtLZS+NZbIjmSAW94Zd4v5i5/N0z4DT1oeVbe2SAOAUHALNwDJ/BOhk213YKxgRz0ekERg6iun+sBsbI06cWcgW9+dC/7OK/xSdK0qFA1/uj9GIepUhWd1Asw=,iv:mQtTSCgQlRS9UEEiY5Ih3ZA8Mdogi9j9wYAqMN+X4Qw=,tag:FBEym8ZS4f2SKNY9aU9xZg==,type:str]
    redirectURL: ENC[AES256_GCM,data:qH0KfEv4t6rlhoDpxIor5gJKZ2VYEG/ctC5bgwNlEgW+ywv6heI65dAezyg=,iv:TFufmcMqc62enE7jvR6GIpa3WYBunIHUba3SDdwuv60=,tag:yDyRJznMlzo6uda8o/Qfzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R0JraUZkZmhNMFdVZjNv
            bXd1VGhkcnZvRFZyb1g2cTdpL0NnNjd5OVFJCmZlV0xWVlcvZGZJaTkwMlFnZFZT
            M3RyaDZRYzVwT1ZmV2NEM1ZrS1hqRU0KLS0tIE1BYnZIdkxNNlVrTDgrbjJYbFcw
            VTRTQmVlUjBHdWpmbkJkUmFvbE0zdjQKki+VuvaOaDY3C/2QiQzmBRf4U4GpEa87
            qqRCXZiIKU1GDsfWAM8Az3onm0MFhRwZK4DRoWVuP8I8Fz24WT+bgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T03:41:19Z"
    mac: ENC[AES256_GCM,data:Og+vGCyOO5R7eAed9b6a0ixy1WK+zd0BZKkp8JSFg+BoD9/sXYvy9vKT88UbpdoPhM+6JGvxZtSBQMwE1L06fl9u7OrDbV3Xs9grPkqKaWPmh24B3dOyzEqrX2PP9worAf7TSAONWfsf6HCQgVv/+OGErU3TitKiDcSUA5pOPUc=,iv:Tk2ofjBYI9qh1Tnr4rDepWVl3un9wH43rJPsrFRkhIs=,tag:wKZmrrckkxVT6XBlVyeagw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
