apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:jcWXDAev/LM9cGcWXPUQhGYCHo1KGdKutPdICx0IPr67EA3/tDpEQqBQmA4AIW9hialKUHtvk+0eL08f,iv:QRYEof+pbJJlMnTEU1Ky8tjLxHevH0LV/k83RXclx3o=,tag:HpiHQTx8DlK69CNp4h76Ug==,type:str]
    username: ENC[AES256_GCM,data:KmVw2CE=,iv:o6VwRODL9T9SyuIg1AWZKY4+GU2BedCUCrcJcODp8Fs=,tag:AVihLui1PNq4LXHcYFD2Rg==,type:str]
    issuerURL: ENC[AES256_GCM,data:e30H/e0qgWZDCPncbQIzHdPwt12lw4bSQ1L+z76ANsmDakLGgX5Ys0M0lCpeUZY=,iv:+t/FdPVXRitMKU32GT0Qw9FBXspkQ2FaBENIWw4LKM4=,tag:EKb++xw7wEbOi1G6bcUVkQ==,type:str]
    clientID: ENC[AES256_GCM,data:R1X1GS18UxwF0de0/8Sl/7BIn42MJGLa9Vr/lUNNZbm87/L2183gNg==,iv:zYv8yG1RSj47w2CWqk0G5OtCzyABXSoVRMlql9UMZTE=,tag:gGlxpmEUjWp89AzZ45si3w==,type:str]
    clientSecret: ENC[AES256_GCM,data:0uBfYqnNuoCYOHRJGfMvVQHhdper4s4XeJVpPUBtSZRVTxhiIcGQPstxvWZGcAKMFxbpGfKKoVhmwWEMnqp3mCNZN9slxqS4WEYG/PEiYF8CWZbTP2ve6wHTmvngSw7TZmpyXtoj3X5SaSwonVCzXk2c602lAzNTALnJq84oYMc=,iv:/wstMIkgXagQn/Xx/7QGOzfMLi/9XEbbStEkrY8i+hU=,tag:Nk3BdVLkGrlhItu3L8GrRw==,type:str]
    redirectURL: ENC[AES256_GCM,data:R1GvhQkquOgJgPOUQABVCwtCDn+U1GhLg9vlL/iJ6y31F8dbM1J6aNaClKc=,iv:/D00EmduFOu9H0ZWgbFjnpN3cJaSPWIQ0Q0v/pmsOLg=,tag:ekfJVbN1Crjb1+0YsUE1AA==,type:str]
    tokenDuration: ENC[AES256_GCM,data:KUo=,iv:AIlZlimvsm1DiGl0hveubtJz7m2ggAt1PaRi+2SiLTM=,tag:HFnwC7TOOSz4CF5YiDd+6Q==,type:str]
    claimUsername: ENC[AES256_GCM,data:XpWk,iv:Ak0KMDM8L3kEIw3CHCKUi01yhh7X7MJHskCYku2aWo8=,tag:zrel9+GiPnR9GdI7t6rMQw==,type:str]
    claimGroups: ENC[AES256_GCM,data:seg4OI4L,iv:XIPkDaQ8e4ZSlvClyltWKln/IS6AudBIO8zrRbqRZ98=,tag:/0GJpDQwXg4hYr/49PzD9Q==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMVpXZUNkZGc4NDVvRW5h
            QmVOQ1IwMmNlb2U5V1BHQU1zVm1jbUlwTkNBCmRkeExzZml3b3J4alAzWk9FdHV0
            cW0vU0RoOEZiV29qdEZSVm52K3dsUnMKLS0tIGlGcUZyalhucnFOSmFqbE45WEpD
            ZjlHR294Rm8rU29UOXgwSk5ydmZKN0EKac/mea6m4oaMMtCyKnaVvFXBSF3ZsvsA
            nsOPpvw5N7nRCHKtmKQsHj5Vz05qfkIaYP0lrsL22k0SN5a5ZJ9JeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T03:01:19Z"
    mac: ENC[AES256_GCM,data:NALXHNaHXWqHMlcgm1H8IttwiN5b78WimTxqwVggfNoqF2VDakI7K+iiXy5f8JtpPZ8MnU4bZrPU9E9KOirbhF1dY3NCD/yhxSKtHOlmMq+VEjLupIyF54HeDeulIXbJlme8s2tPZGEzHaIl+XkKnCcdt5pO+sFxvEntZZmshhI=,iv:Rd14VkPaPYIGpUD+1H7RdidexERXlneq7pceNjWGTQk=,tag:I8ssGIspJquOX7tlJ39Jeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
