apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-gts-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:vIUsU3BBnG6r7VM68E/PNTqoclpxIes83dFXai3ukpBRS1ZZSNlIGQ==,iv:4blJh4xVXv6NoEYyjDpi4uQ29pdn9NeIF/wU7Ce+iRI=,tag:eEsQ7hwcDy79v48B23TJqQ==,type:str]
data:
    secret: ENC[AES256_GCM,data:KIYm0+p+BLj9mcLYz3wifNwsPsdaVOqM1hTW/2QoBAVBcI8dpg3ol/mtvxNYjfh2yIjg4qBJcPkOHoZP5ePhC19EgOvSvfCJypTVkfbuyVmn5IamfP8XNwSbcgQlI52J7sV6DPAy82zYA+kmE1FO6gv3+yc=,iv:4FlKoJJIbhRYTCdYyw3GU2qs/c0/sMT/48ErZhYX964=,tag:jexjfnorO3mUI81JUraBqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoakY4Z29BNUdDS3cyQmc5
            V3AyVGFmUCtkdmYvdTFYOEpoRWRnaVFWVzJvClR0L2c1K0dnQzEyYmQyWk9Sa1l0
            V2RndnJmVGE3b2NaT1RGN1V0cVpESjgKLS0tIEd6UTNZVWxVcHpBWmZ0SDROem1j
            SzNaeEdNM1lXVWNySGkwSFZkS2ZZUFUKaP2jMMRs2cATDOn0cXf+tOnkJldp/Svl
            TTU1BlLKspKZAS0EvpZLkNgVpEHwnye/ItkxJyLl5wvNc+tSnuO4mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-18T05:23:14Z"
    mac: ENC[AES256_GCM,data:wOWFypbBW1iKtRrt5PusSV0WSJt5U7D1/cqqNDU6Eiu8sE13si7MKAaNlOxHTW5HSREdGx+Hm0a53077vyVqb5nhz1zK6vZYrT4bmNtwCMxjY8qDs6WicQvbdIsnms6fr1ComYpZgiFuP1ZMoP8yTfyGcpWJ/Ax0jmBe8HdWETE=,iv:aPQ3PduoXf5zOccMKZzmhI2awxaD9PK9jsce0gVlL5c=,tag:QHxAMWK4X6yEArwLFluOnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
