---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN}-production"
  namespace: networking
spec:
  privateKey:
    algorithm: ECDSA
    size: 384
  secretName: "${SECRET_DOMAIN}-production-tls"
  issuerRef:
    name: gts-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
