---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "le-production-tls"
  namespace: networking
spec:
  secretName: "le-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
