apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:cV53ziIId+SwpkfYP9r7mglmvIthY2zW,iv:RQJYAt0+44ylO3M2ZzfCLcjq29rtqmKXVHIEsl3sTnU=,tag:SRdkVi02U2qgoYl56yagfA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ntt8OpYl77xwHy5lDAQJJzvDIMX5vcI8fw7IyAfdViQjkzkJ,iv:w/sJP3lP+jg/xd2LDRPKFdzHnwdn30eOKFY6e8Q5JxU=,tag:o8xMOOfU7/MJ2EO+yCzzLA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1UwS+ZS/0As3P5IpaA==,iv:C1JOgwjrayF9wjqRN1ggs4eF5zZrtTKYGIRjd7EFq58=,tag:eE0oYzIwRbZRl2wah/MUYQ==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:4oiX+vXZt4Y=,iv:1NhglDZuftWq1lhncuhdj4tBOrxI+ZVFDPY/hOdOSVs=,tag:vFOkgImdbtkLn+OiBrGyTA==,type:str]
    SECRET_SMTP_RELAY: ENC[AES256_GCM,data:i18W2TnsRUMblo6biHVSHiaFkmI=,iv:RqRQoPktSke7vq367z3pNLsagjcyd9mzzpDUpAfFcyA=,tag:ym+Alu0iN7J34RSm1wYulA==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:jZ2yX0Pa4KkvxnadLsYyhec+Q43Nlz5y0AcvTlh4HLQ=,iv:/98O70YPvFFTEUScPxUfudRRT2dNHhtTq00jyFL/GaI=,tag:aPOmYqNxMPldU0m9zCYyrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18l9t76xcvq8tjg8mu38w7xpjswader4j0e3yxlpsyr96l7wdkc5src06l6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bUVDN2pZZEk0MDgzdjhF
            cFU3WXZTMmNuRUtJWHRuQVBIUnBNYm1nVWdnCmRjMTZ0WFF5L0NGL1V1enBvdmdV
            aHphUDBnWDdoZXBzZWhtSDRuLzFyL2MKLS0tIFlwQkFjWjZNK2NTaHBweFBCb2c4
            YmxKb2wyL292Vkk4TWxnenFVUEt3S1kKJjO6/EP1tLDlecV11fphL1a967Btzbtz
            +39JKfek3jNwqXYk4IBldK+Rye8kUfo0eJI8tXWE12MQuqwMuIwkqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-27T19:08:48Z"
    mac: ENC[AES256_GCM,data:TpXKeTwu0Ib3hEHjiDwPrMwvVjmKT4z/VInA+4V3u8SNd2R6oJB7IzCAgvG2Li/i4cVQOyiEhatohl7tPEhj3ZGTY1A/g0WeUA9uFAaPuKnc1RYfLMy2IdC0F4iTcqw5rPDS8kSEqy8EdDIlunbiP6u4KoQpoqUquBUjxDAT/fE=,iv:fbVgIp0G8H0xnGgLPL04dTZQmG3U064+QFMABdSHH4g=,tag:ujcDym/la9NHaSue/ii2Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
