
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 6.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: angelnu-helm-charts
        namespace: flux-system
  #See https://github.com/angelnu/helm-charts/blob/main/charts/apps/pod-gatewa/values.yaml
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      # I am using dev version for testing - others should be using latest
      tag: latest
    DNS: 172.16.1.1

    service:
      vpn:
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.40.12"
        externalTrafficPolicy: Cluster
        ports:
          shadowsocks:
            enabled: true
            port: 8388

    addons:
      vpn:
        enabled: true
        type: gluetun
        gluetun:
          image:
            repository: docker.io/qmcgaw/gluetun
            tag: latest
        env:
        - name: VPN_INTERFACE
          value: wg0
        - name: SHADOWSOCKS
          value: "on"
        - name: FIREWALL
          value: "off"
        - name: DOT
          value: "off"
        - name: SERVER_CITIES
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: SERVER_CITIES
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: WIREGUARD_PRIVATE_KEY
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: WIREGUARD_ADDRESSES
        - name: VPN_SERVICE_PROVIDER
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: VPN_SERVICE_PROVIDER
        - name: VPN_TYPE
          valueFrom:
            secretKeyRef:
              name: vpn-gateway
              key: VPN_TYPE
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(wget -q -O- https://ipinfo.io/country) == 'BE' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3

    podAnnotations:
      configmap.reloader.stakater.com/reload: vpn-gateway-pod-gateway
      secret.reloader.stakater.com/reload: vpn-gateway-vpnconfig

    routed_namespaces:
      - downloads

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: wg0
      VPN_INTERFACE_MTU: "1400"
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: "2049"
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1

    webhook:
      gatewayAnnotation: setGateway
      gatewayDefault: false
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: latest
