---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: thanos
        group: guarded
        url: 10.43.0.10
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: thanos-query-frontend.monitoring.svc.cluster.local
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
